### PR TITLE
Feature 308: Update Job Fields

### LINKED ISSUE #308: Edit Job "master" fields.
Users would like to edit certain data fields on a Job from the APP (not set up new jobs, but edit existing jobs).   It would likely be under the "Account" menu as it would be accessed infrequently. 
User would select the Job from a drop-down and then could edit the following fields:
No
Description
Person_Responsible   (selection from Resources filter:type = Person) Resources (web services endpoint)
Supervisor (Project_Manager) (selection from UserID table)JobProjectManager (web services endpoint)
Status:
Starting_Date  (calendar selection)
Ending_Date (calendar selection)
Pig_Source_Flow

The APP would show the current values for these fields and would allow the user to edit (change).   
Micah - draw up a wire frame for this new APP page.

### PR DESCRIPTION
**Pull request by mwoelfel13**
Fix #308 - There are a few areas I need to touch up but I've successfully been able to update most of the fields designated in the requirements. I need to spend a little more time fixing the project manager lookup as well as limiting which users can see this information. For right now we can test the update is working properly on your end.

### CODE REVIEW

**Comment by KAMogler** [comment]
On Job selection, need to see both Job No. and Description.
image

**Comment by mwoelfel13** [comment]
OK that change has been made.

**Comment by mwoelfel13** [comment]
I just deployed the latest changes, it should be ready in a few minutes.

**Comment by KAMogler** [comment]
Matt,  I can't get past the first screen.  When I select the Table updates it brings me right back to this page.  
image

**Comment by mwoelfel13** [comment]
Should be fixed now

**Comment by mwoelfel13** [comment]
switching select group page to use jobcard endpoint

**Pull request merged**
