### PR TITLE
Filtering /JobCard on status !== completed

### PR DESCRIPTION
**Pull request by mwoelfel13**

### CODE REVIEW

**Comment by KAMogler** [comment]
It doesn't look like it's filtering basis the User Job Posting Group selection.  I selected just Pig Jobs.    This may also help improve the latency if users only look for "their" relevant jobs.

**Comment by mwoelfel13** [comment]
- [ ] Add user filters to JobCard endpoint

**Comment by mwoelfel13** [comment]
I pushed a change to filter on the jobcard search page

**Comment by mwoelfel13** [comment]
The issue with using the that endpoint is it does not contain the fields "Site" and "Job_Posting_Group" -> the two fields we use to filter. Are we able to add these fields? If not you'll have to decide if you want to use this new endpoint or the /JobCard endpoint.

**Comment by KAMogler** [comment]
I prefer not to use the new endpoint but to use the JobCard endpoint as it's the standard for NAV.   I'm good to push this to PROD as is.

**Pull request merged**
